✨ Minecraft Bot 自動化腳本教學 ✨


📂 檔案下載連結   https://drive.google.com/file/d/1GQrZJS5ttZ8gX57ZTf0hotKSHyNoAAMc/view?usp=drive_link
🆕 V9  2024\10\30 18:10PM 
🛠️ 更新內容:

版本    日期
 V9  2024\10\30 18:10PM  修復 DC問題  (config 有更改!)
 V8  2024\10\30 2:49AM  新增驗證系統 錯誤回報通知 
 V6  2024/10/22 04:29 小更新
 V7  2024/10/23 1:47AM  創立bot .s 一個英文字 按下TAB自動補全

⚠️【V8】之後 請一定要看這教學
  ⚠️⚠️⚠️先別打開程式，第3️⃣點特別重要⚠️⚠️⚠️ 
   建議一律使用 "PowerShell" 開啟Bot 出現錯誤 都會回報錯物 截圖 傳給ED
1️⃣ 此次更新新增個檔案 key.txt (可以直接自己在資料夾新增一個)
2️⃣ 請先設定好 key.txt   在 這個txt鐘輸入序號,儲存後就可以開啟程式了
3️⃣ 如果要關閉Bot 請使用 CTRL +C 2 次 絕對不要直接按＂Ｘ＂關閉　如果按了 序號會無法使用要通知 ED 時間不會補
 
📖 簡介
這是一個為 Minecraft 設計的自動化腳本，專門用來幫助你自動完成伺服器內的日常操作，如自動建築、清空背包和轉分流等。

⚠️ 請務必遵守伺服器規則。使用該腳本視為同意，違規導致帳號被封禁，本人不負責。

⚙️ 安裝與設定
1️⃣ 初次設定
下載並解壓縮文件後，將 build 資料夾內的 Bot_ID 修改為你要使用的 Bot ID。

如果發現閃退，請使用 Powershell(Win + R 然後輸入 powershell) 開啟，並將錯誤截圖上傳至 Discord 反饋。
使用 powershell開啟Bot的方式:
  打開 powershell 之後 ,複製程式所在的資料夾路徑  
  然後
 1. cd 路徑 
 2. 輸入 ED　按下鍵盤TAB   
 3. 出現 ED_litematicbot.exe 按下Enter 
 4. 這樣就打開Bot了 然後就是按照教學的部分登入 遇到錯誤之後不會閃退 把錯誤上傳至DC 如果是 config setting 錯誤 請看下方自行解決

⚠️ 注意：請先確認 config、setting 和 build 這三個文件均已正確修改再報告錯誤。

如果遇到 config 或 setting 錯誤，請使用以下範本進行修改：
2️⃣ Config 教學
以下是 config.json 的基本配置範本，根據你的需求進行修改：

{
  "ip": "你的伺服器IP",            # 伺服器的 IP
  "version": "伺服器版本",         # Minecraft 伺服器版本
  "usernames": "你的Bot名稱",      # Bot 的名稱
  "DcID": "你的Discord ID",        # Discord ID
  "whitelist": "白名單玩家",       # 可多位玩家
  "owner": "你的名稱",             # Bot 的操作主要用戶
  "webhookId": "你的Discord webhookId",  # Discord 房間的 webhookId
  "webhookToken": "你的Discord webhook Token"  # Discord 房間的 Token
}

3️⃣ Setting 教學


{
   "log": false,        # 是否輸出 BOT 的訊息
   "Work": false,       # 是否啟用自動建築功能
   "WorkingServer": 10  # 啟用 Work 後檢查伺服器是否存在分流錯誤
}

🛠️ 終端機指令教學
請注意以. 開頭 (點 空白)


1️⃣ 登入Bot
.start [ID]  或者 .s [ID] 
# 範例: .start ED_Xian .s ED_Xian

2️⃣ 讓Bot說話
.say botId 訊息 或者指令
# 範例: .say ED /tpa ED

3️⃣ 關閉Bot
.stop [ID]  
# 範例: .stop ED_Xian 

🛠️ 指令教學
以下是遊戲內白名單玩家與 Bot 的常用指令格式及範例：

1️⃣ 轉分流
/m bot server [數字]
# 範例: /m ED server 3

2️⃣ 清空包包
/m bot dropall
# 範例: /m ED dropall

3️⃣ 自動蓋圖
/m bot build [x] [y] [z] [藍圖名稱.副檔名]
# 範例: /m ED build 10 10 10 ED.litematic 或 /m ED build 10 10 10 ED.nbt


⚠️ 注意事項
伺服器 IP 和版本：請確保正確填寫伺服器的 IP 和 Minecraft 版本，避免連接失敗。
指令格式：所有指令均以 /m bot 開頭，後面接具體的操作參數。
白名單：你可以在 whitelist 中添加多個玩家的 ID，允許他們與 Bot 互動（如接受 TPA 請求）。

❓ 常見問題
1️⃣ Bot 閃退問題
使用 Powershell 啟動，並將錯誤截圖發送至 Discord 進行反饋。
2️⃣ 配置文件錯誤
確認 config 和 setting 文件格式正確，參照上面的範例進行調整。

